DECLARE 
	-- DISEASE ID
	v_did nvarchar2(10) := '{{DISEASE_ID}}';
	-- SYSTEM ID
	v_rid nvarchar2(32) := '{{REPORT_ID}}';
    v_sid nvarchar2(32);
	c int;
BEGIN
SELECT SYSTEM_ID INTO v_sid FROM REPORT WHERE ID = v_rid AND REVISE_HISTORY=1;
-- 通報單
DELETE FROM REPORT WHERE SYSTEM_ID = v_sid;
-- 研判結果
DELETE FROM REPORT_DETERMINED WHERE SYSTEM_ID = v_sid;

DELETE FROM REPORT_CONTACT_INFO WHERE SYSTEM_ID = v_sid;

DELETE FROM REPORT_SYMPTOMS WHERE SYSTEM_ID = v_sid;

-- 檢驗結果
DELETE FROM SAMPLE_RESULT WHERE BARCODE IN (SELECT SAMPLE_ID FROM REPORT_SAMPLE WHERE SYSTEM_ID = v_sid);
DELETE FROM SAMPLE_RESULT_PATHOGEN WHERE BARCODE IN (SELECT SAMPLE_ID FROM REPORT_SAMPLE WHERE SYSTEM_ID = v_sid);
DELETE FROM SAMPLE_RESULT_ANTIBODY WHERE BARCODE IN (SELECT SAMPLE_ID FROM REPORT_SAMPLE WHERE SYSTEM_ID = v_sid);
-- 送驗單
DELETE FROM REPORT_SAMPLE WHERE SYSTEM_ID = v_sid;

-- 主要症狀
DELETE FROM REPORT_SYMPTOMS WHERE SYSTEM_ID = v_sid;
-- 增補欄位
   SELECT COUNT(*) INTO c FROM USER_TABLES WHERE TABLE_NAME = UPPER('REPORT_SUPPLEMENT_{{DISEASE_ID}}');
   IF c = 1 THEN
      EXECUTE IMMEDIATE 'DELETE FROM REPORT_SUPPLEMENT_{{DISEASE_ID}} WHERE SYSTEM_ID = :sid' using v_sid;
   END IF;

-- 刪除通報單異動紀錄
DELETE FROM REPORT_FIELD_DIFF WHERE ID IN (SELECT LOG_ID FROM REPORT_FIELD_DIFF_SUMMARY WHERE SYSTEM_ID = v_sid);
DELETE FROM REPORT_FIELD_DIFF_SUMMARY WHERE SYSTEM_ID = v_sid;

END;
